name: Code Coverage
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-8-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-8-gradle
      - name: Build
        run: ./gradlew test
      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          directory: build/reports/jacoco/
